### ISSUE TITLE
t.at is not a function

### ISSUE THREAD

**Issue by alex-cplee** [AUS-DOH-Safety-and-Quality/PowerBI-Funnels#160]
Hi HQIU,

Can you fix the error "t.at is not a function"? We are using an older version of Power BI Desktop.

Thanks in advance
Alex

**Comment by andrjohns** [comment]
What version of the visual do you have? If it's below 1.5.2.1, then you just need to wait until AppSource begins distributing the [latest version](https://appsource.microsoft.com/en-us/product/power-bi-visuals/healthdepartmentwa1667894240640.powerbi-funnel-charts?tab=DetailsAndSupport)

**Comment by alex-cplee** [comment]
Thanks I will wait patiently for the next version
